import maya.cmds as cmds

def add_stetch_squash(sl):
    """
    @ add stretch squash controller. on selected poly objects.
    add lattice non linear etc etc.
    @ param sel(list): poly mesh objects list
    """
    if not sl:
        raise RuntimeError('Error:- no object to add stretch squash')
sl = cmds.ls(sl=True)        
for each in sl:
    cmds.makeIdentity(each, apply=True, t=1, r=1, s=1, n=0)
    myLattice = cmds.lattice(each, dv=(6,6,6),oc=True)
    myGroup1 = cmds.createNode('transform', n='FFD_Base_RG')
    myGroup2 = cmds.createNode('transform', n='STSQ_FFD_SETUP')
    cmds.parent(myLattice[1], myLattice[2], myGroup1)
    cmds.parent(myGroup1, myGroup2)
    cmds.hide(myGroup2)
    myStretchSquash = cmds.nonLinear(each, typ='squash', lowBound=-1, highBound=1)
    squash = cmds.rename(myStretchSquash[0], 'MID_STSQ')
    squashHandle = cmds.rename(myStretchSquash[1], 'MID_STSQ')
    cmds.hide(squashHandle)
    myCluster = cmds.cluster(each)
    ctrlGrp1 = cmds.createNode('transform',n='MID_STSQ_RG')
    myController = cmds.circle(nr=(0, 0, 1), c=(0, 0, 0), r=2, ch=False, n='MID_STSQ_CTRL')
    cmds.parent(myController[0], ctrlGrp1)
    # cmds.delete(cmds.parentConstraint(myCluster, ctrlGrp, mo=False))
    cmds.delete(myCluster)
    cmds.color(ud=1)
    cmds.parent(squashHandle,myController)
    cmds.setAttr(myController[0]+'.v',l=True, k=False, cb=False)
    cmds.setAttr(myController[0]+'.sx',l=True, k=False, cb=False)
    cmds.setAttr(myController[0]+'.sy',l=True, k=False, cb=False)
    cmds.setAttr(myController[0]+'.sz',l=True, k=False, cb=False)
    cmds.addAttr(myController[0], ln='STSQ', min=-10, max=10, dv=0, k=True)
    cmds.setDrivenKeyframe(squash+".factor", cd=myController[0]+".STSQ", dv=0, v=0)
    cmds.setDrivenKeyframe(squash+".factor", cd=myController[0]+".STSQ", dv=10, v=-1)
    cmds.setDrivenKeyframe(squash+".factor", cd=myController[0]+".STSQ", dv=-10, v=1)
    myStretchSquash = cmds.nonLinear(each, typ='squash', lowBound=0, highBound=3)
    squash = cmds.rename(myStretchSquash[0], 'UP_STSQ')
    squashHandle = cmds.rename(myStretchSquash[1], 'UP_STSQ')
    cmds.setAttr(squashHandle+'.ty',-1)
    cmds.hide(squashHandle)
    cmds.parent(squashHandle,myController)
    myCluster = cmds.cluster(each)
    ctrlGrp = cmds.createNode('transform', n='UP_STSQ_RG')
    myArrow = cmds.curve(d=1,p=[(1, 0, 2), (-1, 0, 2), (-1, 0, 0), (-2, 0, 0), (0, 0, -3), (2, 0, 0), (1, 0, 0), (1, 0, 2)], n='UP_STSQ_CTRL')
    cmds.parent(myArrow, ctrlGrp)
    # cmds.delete(cmds.parentConstraint(myCluster, ctrlGrp, mo=False))
    cmds.delete(myCluster)
    cmds.setAttr(ctrlGrp+'.rx',-90)
    cmds.setAttr(ctrlGrp+'.ry',90)
    cmds.setAttr(ctrlGrp+'.ty',10)
    cmds.setAttr(myArrow+'.tx',l=True, k=False, cb=False)
    cmds.setAttr(myArrow+'.ty',l=True, k=False, cb=False)
    cmds.setAttr(myArrow+'.rx',l=True, k=False, cb=False)
    cmds.setAttr(myArrow+'.ry',l=True, k=False, cb=False)
    cmds.setAttr(myArrow+'.rz',l=True, k=False, cb=False)
    cmds.setAttr(myArrow+'.sx',l=True, k=False, cb=False)
    cmds.setAttr(myArrow+'.sy',l=True, k=False, cb=False)
    cmds.setAttr(myArrow+'.sz',l=True, k=False, cb=False)
    cmds.setAttr(myArrow+'.v',l=True, k=False, cb=False)
    cmds.transformLimits( tz=(-2.5,2.5), etz=(True, True) )
    cmds.setDrivenKeyframe(squash+".factor", cd=myArrow+".tz", dv=0, v=0)
    cmds.setDrivenKeyframe(squash+".factor", cd=myArrow+".tz", dv=2.5, v=.5)
    cmds.setDrivenKeyframe(squash+".factor", cd=myArrow+".tz", dv=-2.5, v=-.5)
    cmds.parent(myGroup2,ctrlGrp,myController)
    myStretchSquash = cmds.nonLinear(each, typ='squash', lowBound=-3, highBound=0)
    squash = cmds.rename(myStretchSquash[0], 'DN_STSQ')
    squashHandle = cmds.rename(myStretchSquash[1], 'DN_STSQ')
    cmds.setAttr(squashHandle+'.ty',1)
    cmds.hide(squashHandle)
    cmds.parent(squashHandle,myController)
    myCluster = cmds.cluster(each)
    dnctrlGrp = cmds.createNode('transform', n='DN_STSQ_RG')
    myArrow = cmds.curve(d=1,p=[(1, 0, 2), (-1, 0, 2), (-1, 0, 0), (-2, 0, 0), (0, 0, -3), (2, 0, 0), (1, 0, 0), (1, 0, 2)],n='DN_STSQ_CTRL')
    cmds.parent(myArrow, dnctrlGrp)
    # cmds.delete(cmds.parentConstraint(myCluster, dnctrlGrp, mo=False))
    cmds.delete(myCluster)
    cmds.setAttr(dnctrlGrp+'.rx',90)
    cmds.setAttr(dnctrlGrp+'.ry',90)
    cmds.setAttr(dnctrlGrp+'.ty',-10)
    cmds.setAttr(myArrow+'.tx',l=True, k=False, cb=False)
    cmds.setAttr(myArrow+'.ty',l=True, k=False, cb=False)
    cmds.setAttr(myArrow+'.rx',l=True, k=False, cb=False)
    cmds.setAttr(myArrow+'.ry',l=True, k=False, cb=False)
    cmds.setAttr(myArrow+'.rz',l=True, k=False, cb=False)
    cmds.setAttr(myArrow+'.sx',l=True, k=False, cb=False)
    cmds.setAttr(myArrow+'.sy',l=True, k=False, cb=False)
    cmds.setAttr(myArrow+'.sz',l=True, k=False, cb=False)
    cmds.setAttr(myArrow+'.v',l=True, k=False, cb=False)
    cmds.transformLimits( tz=(-2.5,2.5), etz=(True, True) )
    cmds.setDrivenKeyframe(squash+".factor", cd=myArrow+".tz", dv=0, v=0)
    cmds.setDrivenKeyframe(squash+".factor", cd=myArrow+".tz", dv=2.5, v=.5)
    cmds.setDrivenKeyframe(squash+".factor", cd=myArrow+".tz", dv=-2.5, v=-.5)
    cmds.parent(dnctrlGrp,myController)
    cmds.reorder('STSQ_FFD_SETUP', r=3)
    cmds.reorder('DN_STSQ1',r=-1)
    
    

     if __name__ == '__main__':
        add_stetch_squash(cmds.ls(sl=True))